/** Static v8 design samples; no code from the source is executed.
 * Source SHA256: b5eefc9739ab1d995e4c10cbb0e90c8dcb2fa099cc4b707ec47a574a46b2af87
 */
export const taskGateContexts = {
  g3: {
    "proposed-change": [
      "资产差异",
      "签名配置差异",
      "展示 AI 准备提交的配置变更，并核对它是否越过配置冻结边界。",
      "获批版本",
      "signing.algorithm = ed25519\nsigning.key_source = release-vault\nartifact = candidate-v0.8.2",
      "候选修改",
      "signing.key_source → isolated-vault\nsigning.retry_policy → verify-once\n影响：仅 build-and-sign 节点",
      "artifact:signing-config@sha256:4c2f\nproposal:patch-91\ndecision:decision-42",
    ],
    "validation-result": [
      "证据回执",
      "安全扫描结果",
      "核对既有安全证据是否仍适用于准备修改的候选包。",
      "支持的 Claim",
      "候选包未发现阻断级安全问题\nVerdict: PASS\nScope: artifact sha256:91ab…",
      "有效性",
      "规则集：market-security@2026.09\n记录时间：14:03:18\n配置变化不改变已扫描 artifact",
      "evidence:evidence-77\nworkflow_run:workflow-v3/run-08\nspan:security-scan",
    ],
    "governing-decision": [
      "决定回执",
      "配置冻结决定",
      "核对用户此前授予的权限边界，以及当前候选修改是否与之冲突。",
      "用户原始决定",
      "“进入验证阶段后冻结签名配置；如需修改，必须重新请示。”",
      "结构化效果",
      "authority: user\nforbid: autonomous mutation of signing.*\nstatus: ACTIVE",
      "decision:decision-42\nsource_message:msg-184\nir_revision:control-ir@38",
    ],
  },
  g5: {
    "trigger-record": [
      "缺口报告",
      "覆盖率缺口报告",
      "说明为什么文档覆盖率偏差被升级为当前 Gate。",
      "缺失场景",
      "Node 22 长期兼容性\n离线安装失败恢复",
      "影响判断",
      "主要发布路径不受影响\n后续支持成本仍不确定",
      "report:coverage-gap@18\nwave:wave-4\ngate:G-5",
    ],
    "proposed-change": [
      "资产差异",
      "发布说明差异",
      "核对 AI 准备保留的发布说明，以及被明确登记为残余风险的内容。",
      "计划目标",
      "28 个文档场景\n全部提供可验证示例",
      "候选结果",
      "26 个场景已完成\n2 个场景进入残余风险",
      "artifact:release-notes@sha256:83ce\nproposal:patch-104\ngate:G-5",
    ],
    "validation-result": [
      "证据回执",
      "主路径验证结果",
      "核对缺失场景是否会影响当前发布主路径。",
      "支持的 Claim",
      "主要安装与升级路径均有可重放证据\nVerdict: PASS",
      "证据边界",
      "不覆盖 Node 22 长期兼容性\n不覆盖离线恢复说明",
      "evidence:evidence-93\nworkflow_run:docs-v2/run-04\nspan:main-path-doc-check",
    ],
    "governing-decision": [
      "决定回执",
      "文档完成标准",
      "核对用户允许哪些非关键缺口作为残余风险进入后续 Gate。",
      "用户原始决定",
      "“主路径必须完整；边缘场景可以登记风险，但不能无声遗漏。”",
      "结构化效果",
      "required: main path coverage\nallow: explicit residual risk\nstatus: ACTIVE",
      "decision:decision-51\nsource_message:msg-209\nir_revision:control-ir@44",
    ],
  },
  g6: {
    "trigger-record": [
      "控制关系",
      "Gate 依赖关系",
      "核对最终发布 Gate 为什么尚未具备可决条件。",
      "未关闭依赖",
      "G-3 · 签名配置重试\nG-5 · 文档覆盖率偏差",
      "当前效果",
      "候选包保持隔离\n不会生成发布授权请求",
      "plan_run:plan-v4/run-08\ngate:G-6\ndepends_on:G-3,G-5",
    ],
    "proposed-change": [
      "资产清单",
      "候选包清单",
      "核对最终 Gate 将要授权的精确产物，而不是可变的“最新候选包”。",
      "候选对象",
      "publish-candidate-v0.8.2.tgz\nsha256:91ab…",
      "当前状态",
      "ISOLATED\n尚未绑定最终发布凭据",
      "artifact:candidate@sha256:91ab\ngate:G-6\nrevision:immutable",
    ],
    "validation-result": [
      "证据回执",
      "最终验证摘要",
      "汇总最终发布所需证据；前置 Gate 改变产物后必须重新计算。",
      "当前状态",
      "WAITING_DEPENDENCIES\nG-3、G-5 未关闭",
      "禁止行为",
      "不得沿用失效证据\n不得自动发布",
      "evidence_set:final-set@pending\nplan_run:plan-v4/run-08\ngate:G-6",
    ],
    "governing-decision": [
      "决定回执",
      "发布权限决定",
      "核对公开发布始终要求用户明确授权的既有决定。",
      "用户原始决定",
      "“可以自主生成候选包，但公开发布必须由我确认。”",
      "结构化效果",
      "authority: user\naction: public_publish\nstatus: ACTIVE",
      "decision:decision-12\nsource_message:msg-41\nir_revision:control-ir@9",
    ],
  },
} as const;
