/** Regenerate opt-in Crystra theme from the reviewed source snapshot. */
import { readFileSync, writeFileSync } from "node:fs";
import { format } from "prettier";
const source = new URL("../design/crystra.tokens.json", import.meta.url);
const tokens = JSON.parse(readFileSync(source, "utf8"));
const scope = '.wsr-bi[data-crystra-theme="dark"]';
const lines = [
  "/* Generated by scripts/sync-crystra-design.ts. No host Input selectors. */",
  `${scope} {`,
  "  color-scheme: dark;",
  "  color: var(--color-text-primary);",
];
for (const [name, spec] of Object.entries(tokens.color.roles) as [
  string,
  { value: string },
][])
  lines.push(`  --color-${name}: ${spec.value};`);
const aliases: Record<string, string> = {
  "surface-section": "background-workspace",
  "surface-panel": "background-card",
  "surface-inset": "background-inset",
  "surface-raised": "background-floating",
  "content-primary": "text-primary",
  "content-secondary": "text-secondary",
  "content-muted": "text-muted",
  "border-default": "border-default",
  "border-strong": "border-strong",
  "interaction-accent": "interaction-primary",
  "interaction-selection": "interaction-selected",
  "status-error": "status-error-solid",
  "status-attention": "status-warning-solid",
  "status-available": "status-success-solid",
};
// Only bind aliases that are present in the reviewed vocabulary.
for (const [alias, role] of Object.entries(aliases)) {
  if (!tokens.color.roles[role]) throw new Error(`Unknown color role: ${role}`);
  lines.push(`  --${alias}: var(--color-${role});`);
}
for (const [name, v] of Object.entries(tokens.typography) as [
  string,
  { size: number; lineHeight: number; weight: number },
][]) {
  lines.push(
    `  --crystra-type-${name}-size: ${v.size}px;`,
    `  --crystra-type-${name}-line: ${v.lineHeight}px;`,
    `  --crystra-type-${name}-weight: ${v.weight};`,
  );
}
const geometry = JSON.parse(
  readFileSync(
    new URL("../design/crystra.geometry.json", import.meta.url),
    "utf8",
  ),
) as { groups: Record<string, Record<string, string>> };
for (const group of Object.values(geometry.groups))
  for (const [name, value] of Object.entries(group))
    lines.push(`  --${name}: ${value};`);
lines.push("}");
for (const name of Object.keys(tokens.typography)) {
  lines.push(
    `${scope} .wsr-typography[data-variant="${name}"]:not([data-host-owned], [data-host-owned] *) { font-size:var(--crystra-type-${name}-size);line-height:var(--crystra-type-${name}-line);font-weight:var(--crystra-type-${name}-weight);letter-spacing:0;text-transform:none; }`,
  );
}
writeFileSync(
  new URL("../packages/bi/src/crystra-theme.css", import.meta.url),
  await format(lines.join("\n") + "\n", { parser: "css" }),
);

// Layout algorithms consume the same reviewed asset as CSS, not a second table.
writeFileSync(new URL('../packages/bi/src/domain/observation-layout-tokens.ts',import.meta.url),
 '// Generated by sync-crystra-design.ts from design/crystra.geometry.json.\nexport const observationLayoutTokens:Record<string,string> = '+JSON.stringify(geometry.groups.observation,null,2)+';\n');

// Keep the host-neutral stylesheet usable without the Crystra theme.
const sharedPath = new URL('../packages/bi/src/shared.css', import.meta.url);
let shared = readFileSync(sharedPath, 'utf8');
shared = shared.replace(/  \/\* Generated trace geometry default \*\/\n  --component-trace-zoom-inset:.*\n/g, '');
shared = shared.replace('.wsr-bi {', '.wsr-bi {\n  /* Generated trace geometry default */\n  --component-trace-zoom-inset: '+geometry.groups.observation['component-trace-zoom-inset']+';');
writeFileSync(sharedPath, shared);
